services:
  postgres:
    image: postgres:16-alpine
    container_name: resource-booking-postgres
    environment:
      POSTGRES_DB: resource_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_resource_booking:/var/lib/postgresql/data

volumes:
  pgdata_resource_booking:
